# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CityVizor
email: cityvizor@otevrenamesta.cz
description: CityVizor je aplikace na přehledné zveřejnění výdajů obcí!
baseurl: "/CityVizor"
url: ""

# Build settings
markdown: kramdown

# Main menu
navigation:
- text: O aplikaci
  url: o-aplikaci/
  id: o-aplikaci
- text: Návody
  url: navody/
  id: navody
- text: Data
  url: data/
  id: data
- text: Kontakt
  url: kontakt/
  id: kontakt
  
# Gems
gems: 
 - jekyll-redirect-from
 
# Libraries
cdn_libs:
    css:
      - https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.4/foundation.min.css
      - https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css
      - https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.2.2/motion-ui.min.css
    js:
      - https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/jquery.countdown/2.2.0/jquery.countdown.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.4/foundation.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.2.2/motion-ui.min.js
