version: "3.8"

services:
    # We don't need the nginx container when developing. This effectively removes it.
    # https://stackoverflow.com/a/45385268/5127149
    proxy:
        image: tianon/true
        command: ""
        entrypoint: ""
        ports: []
    cityvizor-client:
        image: tianon/true
        command: ""
        entrypoint: ""
        ports: []
    cityvizor-server:
        build:
            target: dev
        command: -w db.cityvizor.cesko.digital -a -m server-dev
        ports:
            - 3000:3000
        volumes:
            - ./server:/user/src/app
            - /user/src/app/node_modules
    cityvizor-worker:
        build:
            target: dev
        command: -w db.cityvizor.cesko.digital -a -m worker-dev
        volumes:
            - ./server:/user/src/app
            - /user/src/app/node_modules
    backend-kotlin:
        ports:
            - 4203:8080
    landing-page:
        build:
            target: dev
        ports:
            - 4202:8080
        volumes:
            - ./landing-page/src:/user/src/app/src
            - ./landing-page/cfg:/user/src/app/cfg
