version: '3.1'

services:
  cityvizor-server:
    image: cityvizor
    build: .
    command: node server/dist/server.js
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes: 
      - ./server/environment/environment.production.js:/user/src/app/server/environment/environment.production.js:ro
      - ./data:/home/node/app/data
    depends_on: 
      - postgres

  cityvizor-worker:
    image: cityvizor
    build: .
    environment:
      NODE_ENV: production
    command: node server/dist/worker.js
    volumes:
      - ./server/environment/environment.production.js:/user/src/app/server/environment/environment.production.js:ro
      - ./data:/home/node/app/data
    depends_on: 
      - postgres
      
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
