version: "2.4"

services:
  proxy:
    image: nginx:1.15.8-alpine
    container_name: nginx.cityvizor.cesko.digital
    ports:
      # Client
      - "4200:80"
      # Redesign
      - "4201:81"
      # Strapi server
      - "1337:1337"
    volumes:
      - ./nginx:/etc/nginx:ro
    environment:
      NGINX_HOST: cityvizor.cesko.digital
      NGINX_PORT: 80

  backend-kotlin:
    image: backend-kotlin
    build: server-kotlin/.
    container_name: backend.cityvizor.cesko.digital
    environment:
      JDBC_URL: jdbc:postgresql://db.cityvizor.cesko.digital:5432/cityvizor
    depends_on:
      postgres:
        condition: service_healthy
      proxy:
        condition: service_started

  cityvizor-server:
    image: cityvizor-server
    build: ./server
    command: node dist/server.js
    container_name: server.cityvizor.cesko.digital
    environment:
      NODE_ENV: local
    volumes:
      - ./data:/user/src/app/data
    depends_on:
      postgres:
        condition: service_healthy
      proxy:
        condition: service_started

  cityvizor-worker:
    image: cityvizor-server
    build: ./server
    command: node dist/worker.js
    container_name: worker.cityvizor.cesko.digital
    environment:
      NODE_ENV: local
    volumes:
      - ./data:/user/src/app/data
    depends_on:
      postgres:
        condition: service_healthy

  cityvizor-client:
    image: cityvizor-client
    build: ./client
    container_name: client.cityvizor.cesko.digital
    environment:
      NODE_ENV: local
    depends_on:
      - proxy

  cityvizor-server-strapi:
    image: cityvizor-server-strapi
    build: ./redesign/server-strapi
    container_name: strapi.cityvizor.cesko.digital
    depends_on:
      - proxy

  cityvizor-redesign-client:
    image: cityvizor-redesign-client
    build:
      context: ./redesign/client-redesign
      args:
        - VUE_APP_API_BASE_URL='http://localhost:1337/citysearch'
        - VUE_APP_CONTENT_API_BASE_URL='http://localhost:1337'
    container_name: client-redesign.cityvizor.cesko.digital
    environment:
      NODE_ENV: local
    depends_on:
      - proxy

  postgres:
    image: postgres:11.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: db.cityvizor.cesko.digital
    environment:
      POSTGRES_DB: cityvizor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./database/demo_dump.sql:/docker-entrypoint-initdb.d/demo_dump.sql
    ports:
      - 5432:5432
