cityvizor_server:
  database_host: 10.0.1.1
  database_name: cityvizor
  database_username: postgres
  database_password: pass
  tag: latest
  create_admin: true

cityvizor_client:
  tag: latest

server_kotlin:
  jdbc_url: jdbc:postgresql://10.0.1.1:5432
  db_user: postgres
  db_pass: pass
  google_secrets_path: /home/ubuntu/cityvizor/server-kotlin/src/test/resources/city_request/test-credentials.json
  tag: latest

landing_page:
  tag: latest

ingress:
  main_host: cityvizor-test.ceskodigital.net
  landing_page_host: landing.cityvizor-test.ceskodigital.net
  
