
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cityvizor-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-snippet: |
      location = / {
        return 302 /landing;
      }
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: cityvizor-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/v2/
            backend:
              serviceName: server-kotlin
              servicePort: 8080
          - path: /api/v1/citysync
            backend:
              serviceName: server-kotlin
              servicePort: 8080
          - path: /api
            backend:
              serviceName: cityvizor-server
              servicePort: 3000
          - path: /landing
            backend:
              serviceName: landing-page
              servicePort: 80
          - path: /
            backend:
              serviceName: cityvizor-client
              servicePort: 80
